[2] (GameUuid) Add a missing existing() method
to fix the following error:

There was 1 error:

1) SymfonyCon\Mastermind\Game\GameUuidTest::test_it_instantiates_an_existing_uuid
Error: Call to undefined method SymfonyCon\Mastermind\Game\GameUuid::existing()