[2] (GameUuid) Add a missing class
to fix the error while running tests:

There was 1 error:

1) SymfonyCon\Mastermind\Game\GameUuidTest::test_it_instantiates_an_existing_uuid
Error: Class 'SymfonyCon\Mastermind\Game\GameUuid' not found

/symfonycon/tests/Game/GameUuidTest.php:12